workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: Codemagic Api Key

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.christianmcalpine.macroapp"
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_PATH: "frontend"
        API_BASE_URL: $API_BASE_URL
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Install CocoaPods
        script: |
          cd $PROJECT_PATH/ios
          pod install

      - name: Set up provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          cd $PROJECT_PATH
          flutter pub get

      - name: Build iOS app
        script: |
          cd $PROJECT_PATH
          flutter build ios --release \
            --dart-define=API_BASE_URL=$API_BASE_URL \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

      - name: Archive and export IPA
        script: |
          xcode-project build-ipa \
            --workspace "$PROJECT_PATH/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $PROJECT_PATH/flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - cp.mcalpine@icloud.com
