workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: Codemagic API Key

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.christianmcalpine.macroapp"
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_PATH: "frontend"
        APP_STORE_APPLE_ID: 6745361330
        API_BASE_URL: $API_BASE_URL
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Get Flutter packages
        script: |
          cd $PROJECT_PATH
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd $PROJECT_PATH/ios
          pod install

      - name: Set up provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          cd $PROJECT_PATH/ios
          LATEST_BUILD=$(app-store-connect get-latest-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $((LATEST_BUILD + 1))

      - name: Build Flutter iOS binary with dart-define
        script: |
          cd $PROJECT_PATH
          flutter build ios --release \
            --dart-define=API_BASE_URL=$API_BASE_URL \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

      - name: Archive with Xcode (signed)
        script: |
          cd $PROJECT_PATH/ios
          xcode-project build-archive \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-path build/ios/xcarchive/Runner.xcarchive

      - name: Export signed IPA
        script: |
          xcode-project export-ipa \
            --archive build/ios/xcarchive/Runner.xcarchive \
            --export-options-plist "$PROJECT_PATH/ios/exportOptions.plist" 

      - name: Inspect final IPA for 120x120 icon
        script: |
          mkdir -p /tmp/ipa_check
          unzip -q build/ios/ipa/*.ipa -d /tmp/ipa_check
          find /tmp/ipa_check -name "*60x60*"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $PROJECT_PATH/flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - cp.mcalpine@icloud.com
